{
  ApplyLeveledListMerge.pas
  
  Sky-Claw Dynamic Patching Script
  Phase 2: Leveled List Merge Automation
  
  This script merges LVLI (Leveled Items), LVLN (Leveled NPCs), and LVSP (Leveled Spells)
  records from loaded plugins into a single merged output plugin.
  
  Usage:
    SSEEdit.exe -IKnowWhatImDoing -script:"apply_leveled_list_merge.pas" <output_plugin_name>
  
  Parameters:
    Param(1) - Output plugin name (optional, defaults to "SkyClaw_Merged.esp")
  
  Generated by: Sky-Claw PatchOrchestrator
  Template version: 2.0
}

unit ApplyLeveledListMerge;

uses mteFunctions, SysUtils, Classes;

var
  outputPlugin: IInterface;
  outputPluginName: string;
  processedCount: Integer;
  skippedCount: Integer;
  errorCount: Integer;
  processedFormIDs: TStringList;

const
  // Record signatures for leveled lists
  SIGN_LVLI = 'LVLI';  // Leveled Item
  SIGN_LVLN = 'LVLN';  // Leveled NPC
  SIGN_LVSP = 'LVSP';  // Leveled Spell
  
  // Output plugin default name
  DEFAULT_OUTPUT = 'SkyClaw_Merged.esp';

{
  Initialize: Called once at the start of script execution.
  Sets up the output plugin and initializes tracking variables.
}
function Initialize: integer;
var
  i: Integer;
  paramValue: string;
begin
  Result := 0;
  processedCount := 0;
  skippedCount := 0;
  errorCount := 0;
  
  // Initialize FormID tracking to prevent duplicates
  processedFormIDs := TStringList.Create;
  processedFormIDs.Sorted := True;
  processedFormIDs.Duplicates := dupIgnore;
  
  AddMessage('=================================================');
  AddMessage('Sky-Claw: Leveled List Merge Script v2.0');
  AddMessage('=================================================');
  
  // Get output plugin name from parameter or use default
  outputPluginName := DEFAULT_OUTPUT;
  
  // Check command line parameters
  for i := 1 to ParamCount do
  begin
    paramValue := ParamStr(i);
    if (Pos('.es', paramValue) > 0) or (Pos('.ESP', paramValue) > 0) then
    begin
      outputPluginName := paramValue;
      Break;
    end;
  end;
  
  AddMessage('Output plugin: ' + outputPluginName);
  
  // Try to load existing plugin first
  outputPlugin := FileByName(outputPluginName);
  
  if Assigned(outputPlugin) then
  begin
    AddMessage('Using existing output plugin: ' + outputPluginName);
  end
  else
  begin
    // Create new plugin
    AddMessage('Creating new output plugin: ' + outputPluginName);
    outputPlugin := AddNewFile(outputPluginName);
    
    if not Assigned(outputPlugin) then
    begin
      AddMessage('ERROR: Failed to create output plugin: ' + outputPluginName);
      Result := 1;
      Exit;
    end;
    
    AddMessage('Output plugin created successfully');
  end;
  
  AddMessage('Processing loaded plugins...');
  AddMessage('-------------------------------------------------');
end;

{
  IsLeveledListRecord: Checks if a record is a leveled list type.
}
function IsLeveledListRecord(e: IInterface): Boolean;
var
  sig: string;
begin
  Result := False;
  sig := Signature(e);
  
  if (sig = SIGN_LVLI) or (sig = SIGN_LVLN) or (sig = SIGN_LVSP) then
    Result := True;
end;

{
  GetFormIDString: Converts a FormID to a string representation.
}
function GetFormIDString(e: IInterface): string;
var
  formId: Cardinal;
begin
  formId := FormID(e);
  Result := IntToHex(formId, 8);
end;

{
  RecordExistsInOutput: Checks if a record with the same FormID exists in output.
}
function RecordExistsInOutput(formIdStr: string): Boolean;
begin
  Result := processedFormIDs.IndexOf(formIdStr) >= 0;
end;

{
  MergeRecord: Merges a single leveled list record into the output plugin.
  Returns True if successful, False otherwise.
}
function MergeRecord(e: IInterface): Boolean;
var
  formIdStr: string;
  recordSig: string;
  newRecord: IInterface;
  editorId: string;
begin
  Result := False;
  
  if not Assigned(e) then
    Exit;
  
  if not Assigned(outputPlugin) then
  begin
    AddMessage('ERROR: Output plugin not assigned');
    Exit;
  end;
  
  formIdStr := GetFormIDString(e);
  recordSig := Signature(e);
  
  // Check if already processed (avoid duplicates)
  if RecordExistsInOutput(formIdStr) then
  begin
    Inc(skippedCount);
    AddMessage(Format('  Skipped duplicate: [%s] %s', [recordSig, formIdStr]));
    Result := True;  // Not an error, just skipped
    Exit;
  end;
  
  // Get Editor ID for logging
  editorId := GetElementEditValues(e, 'EDID');
  if editorId = '' then
    editorId := '<no EDID>';
  
  try
    // Copy record to output plugin
    // wbCopyElementToRecord parameters:
    //   source, destination, asNew, silent
    newRecord := wbCopyElementToRecord(e, outputPlugin, False, True);
    
    if Assigned(newRecord) then
    begin
      // Track processed FormID
      processedFormIDs.Add(formIdStr);
      Inc(processedCount);
      
      AddMessage(Format('  Merged: [%s] %s (%s)', [recordSig, formIdStr, editorId]));
      Result := True;
    end
    else
    begin
      Inc(errorCount);
      AddMessage(Format('  ERROR: Failed to copy [%s] %s (%s)', [recordSig, formIdStr, editorId]));
    end;
  except
    on E: Exception do
    begin
      Inc(errorCount);
      AddMessage(Format('  EXCEPTION: [%s] %s - %s', [recordSig, formIdStr, E.Message]));
    end;
  end;
end;

{
  Process: Called for each record in loaded plugins.
  Handles the actual merging of leveled list records.
}
function Process(e: IInterface): integer;
var
  recordSig: string;
  formIdStr: string;
begin
  Result := 0;
  
  // Skip if not a leveled list record
  if not IsLeveledListRecord(e) then
    Exit;
  
  recordSig := Signature(e);
  formIdStr := GetFormIDString(e);
  
  // Skip records from the output plugin itself
  if GetFileName(GetFile(e)) = outputPluginName then
    Exit;
  
  // Log progress every 50 records
  if (processedCount > 0) and ((processedCount mod 50) = 0) then
  begin
    AddMessage(Format('Progress: %d records merged...', [processedCount]));
  end;
  
  // Merge the record
  if not MergeRecord(e) then
  begin
    AddMessage(Format('Warning: Failed to merge %s record: %s', [recordSig, formIdStr]));
  end;
end;

{
  Finalize: Called once at the end of script execution.
  Reports summary and cleans up resources.
}
function Finalize: integer;
begin
  AddMessage('-------------------------------------------------');
  AddMessage('Merge Summary:');
  AddMessage(Format('  Records merged:  %d', [processedCount]));
  AddMessage(Format('  Records skipped: %d', [skippedCount]));
  AddMessage(Format('  Errors:          %d', [errorCount]));
  AddMessage('-------------------------------------------------');
  
  // Clean up masters from output plugin
  if Assigned(outputPlugin) and (processedCount > 0) then
  begin
    AddMessage('Cleaning masters from output plugin...');
    try
      CleanMasters(outputPlugin);
      AddMessage('Masters cleaned successfully');
    except
      on E: Exception do
      begin
        AddMessage('Warning: Failed to clean masters: ' + E.Message);
      end;
    end;
  end;
  
  // Free resources
  if Assigned(processedFormIDs) then
  begin
    processedFormIDs.Free;
    processedFormIDs := nil;
  end;
  
  // Determine final result
  if errorCount > 0 then
  begin
    AddMessage('WARNING: Errors occurred during merge');
    AddMessage('Please review the output plugin carefully');
    Result := 1;
  end
  else
  begin
    AddMessage('Merge completed successfully');
    AddMessage('Output: ' + outputPluginName);
    Result := 0;
  end;
  
  AddMessage('=================================================');
end;

end.
